config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'

  resources :posts
  resources :users
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'projects' => 'pages#projects'
  get 'account' => 'pages#account'
  get 'admin_panel' => 'pages#admin_panel'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<h1>About me</h1>

app/views/pages/account.html.erb
<section class='account'>
<h1> ACCOUNT </h1>
<table>
<tr>
  <th>Login</th>
  <th><%= current_user.login %></th>
</tr>
<tr>
  <th>Name</th>
  <th><%= current_user.name %></th>
</tr>
<tr>
  <th>Lastname</th>
  <th><%= current_user.lastname %></th>
</tr>
<tr>
  <th>Email</th>
  <th><%= current_user.email %></th>
</tr>

</table>
<div class='avatar'>
<%= image_tag(current_user.avatar) if current_user.avatar.attached? %>
</div>
<div class='center'>
<%= link_to 'Edit', edit_user_registration_path, :class => 'btn' %> 
<%= link_to 'Delete account', user_registration_path , method: :delete, data: { confirm: "You sure? All posts will be permanently deleted with Your account " }, :class => 'btn btn-red btn-anime' %>
</div>
<div>
<h1>Your Posts</h1>
<table>
<% current_user.posts.each do |post| %>

      <div class='post-single'>
        <div class='title-post'><%= post.title %></div>
        <div class='content-post'><%= post.content.first(200) + '...' %></div>
        <div class='account-buttons'>
        <%= link_to 'Read more ', post, :class => 'btn' %>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-red btn-anime' %>
        <%= link_to 'Edit', edit_post_path(post.id), :class => 'btn' %>
        </div>
      </div>
<% end %>
</table>
</div>
</div>

app/views/pages/admin_panel.html.erb
<section class='admin-panel'>
<H1> Users on Your webside </h1>
<div class='permition-table'>
<table>
<% @users.each do |user| %>
  <tr>
    <td class='title-main'><%= user.name.capitalize %></td>
   <td> <%= link_to 'Destroy', user, :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-red btn-anime' %> </td>
    <td><%= link_to 'Edit', edit_user_path(user.id), controller: :edit_admin, :class => 'btn' %>  </td>
    <td> Admin ? =>   
    <%= user.admin ? 'Yes' : 'No' %>
    </td>
  </tr>
<% end %>
</table>
</div>
<h1> Posts on Your webside </h1>
<table>
  <thead>
    <tr>
    <th colspan="3"></th>
    </tr>
  </thead>
    <tr style= 'text-align: center;'>
    <td style= 'width: 200px;'>Tytul postu</td>
    <td style= 'width: 150px;'> Autor </td>
    <td> Action </td>
  </tr>

<% @posts.each do |post| %>
  <tr class='post-single'>
    <td class='title-main'><%= post.title.capitalize %></td>
    <td class='autor-post'><%= post.user.name.capitalize %></td>
    <td><%= link_to 'Czytaj wiecej', post, :class => 'btn' %>
    <%= link_to 'Edit', edit_post_path(post), :class => 'btn' %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-red btn-anime' %>
  </td>
  </tr>
 
<% end %>
</table>
</section>

app/views/pages/contact.html.erb
<h1>Contact with us!</h1>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/projects.html.erb
<h1> My projects </h1>

app/views/pages/show.html.erb
<%= form_with(model: post, local: true) do |form| %>

  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :content %>
  </p>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>