config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'

  resources :posts
  resources :users
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'projects' => 'pages#projects'
  get 'account' => 'pages#account'
  get 'admin_panel' => 'pages#admin_panel'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image, dependent: :destroy 
    has_one_attached :photos, dependent: :destroy 
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @users = User.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, success: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, success: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, danger: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {}) .permit(:title, :content, :image, :user_id, )
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>

<% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</p>
  <%= form.label :Content %>
   <%= form.text_area :content,  :class => "tinymce" %>
<%= tinymce %>
<div class='photos'>
  <%= form.label :photos %>
  <%= form.file_field :photos %>
</div><br>
<div class="actions">
  <%= form.submit({:class => 'btn btn-submit'}) %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post , :class => 'btn' %> |
<%= link_to 'Back', posts_path , :class => 'btn btn-red' %>

app/views/posts/index.html.erb
<div class='post-list'>
  <h1>Posts</h1>
    <table>
      <thead>
        <tr>
        <th colspan="3"></th>
        </tr>
       </thead>
    <% @posts.each do |post| %>
      <div class='post-single'>
        <div class='title-post'><%= post.title %></div>
        <div class='content-post'><%= post.content.first(200) + '...' %><%= link_to '...Read more', post, :class => 'btn btn-small' %> </div>
        <div class='autor-date'>
        <div class='autor-post'>Autor <%= post.user.name.capitalize %></div>
        <div class='post-date'>Last Update <%= post.updated_at.time.to_date %></div>
        </div>
        </div>
    <% end %>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path, :class => 'btn btn-red' %>

app/views/posts/show.html.erb
<section class='post post-single post-page'>
<div class='avatar'>
  
<%= image_tag(@post.user.avatar) if @post.user.avatar.attached? %>


</div>
<div class='title-post'>
    <%= @post.title.html_safe %>
</div>
<div class='content-post'>
    <%= @post.content.html_safe %>
</div>
<div>

<%= image_tag(@post.photos) if @post.photos.attached? %>
</div>
</section>

<%= link_to 'Back', posts_path, :class => 'btn' %>

<% if user_signed_in? %>
<% if current_user.id == @post.user.id%>
<%= link_to 'Edit', edit_post_path(@post), :class => 'btn' %> 
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-red btn-anime' %>
<% end %>
<% end %>