config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'

  resources :posts
  resources :users
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'projects' => 'pages#projects'
  get 'account' => 'pages#account'
  get 'admin_panel' => 'pages#admin_panel'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class='footer'>

</div>

app/views/layouts/_header.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "About Site", about_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
  <li><%= link_to "Projects", projects_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to 'New Post', new_post_path %></li>
    <li><%= link_to "Account ", account_path %></li>
  <div class='user_welcome'> 
  <% if current_user.admin == true %>
    <li><%= link_to "Admin Panel ", admin_panel_path, :id => 'adminStatus' %></li>
  <% end %>
    <li><%= link_to 'Logout ', destroy_user_session_path, method: :delete %></li>
    <li id='menu_welcome'>Welcome <%= current_user.name.capitalize %> </li>
  </div>
  <% else %>
    <li><%= link_to 'Login ', user_session_path %></li>
    <li><%= link_to 'Registration', new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', ' -turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="lib/noty.css" rel="stylesheet">
    <script src="lib/noty.js" type="text/javascript"></script>
     <%= tinymce_assets %>
  </head>
<body>
<p id="notice"><%= notice %></p>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

<%= render 'layouts/header'%>

  <div class='container'>
  <div class='content'>
  <%= yield %>
  </div>
  </div>
<%= render 'layouts/footer'%>
</body>
</html>